# Generated by Django 2.1.3 on 2019-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0011_auto_20190827_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cname',
            name='subject_code',
        ),
        migrations.AddField(
            model_name='cname',
            name='gender',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cname',
            name='Class',
            field=models.CharField(blank=True, choices=[('JSS 1', 'jss_one'), ('JSS 2', 'jss_two'), ('JSS 3', 'jss_three'), ('SSS 1', 'sss_one'), ('SSS 2', 'sss_two'), ('SSS 3', 'sss_three')], max_length=30, null=True),
        ),
    ]
