# Generated by Django 2.1.3 on 2019-08-31 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0017_auto_20190831_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual',
            name='first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first', to='result.QSUBJECT'),
        ),
        migrations.AlterField(
            model_name='annual',
            name='second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='result.QSUBJECT'),
        ),
        migrations.AlterField(
            model_name='annual',
            name='third',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='result.QSUBJECT'),
        ),
        migrations.AlterField(
            model_name='btutor',
            name='created',
            field=models.DateTimeField(default='2019-09-01', max_length=200),
        ),
    ]
