# Generated by Django 2.1.3 on 2019-09-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0023_auto_20190902_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btutor',
            name='created',
            field=models.DateTimeField(default='2019-09-03', max_length=200),
        ),
        migrations.AlterField(
            model_name='btutor',
            name='session',
            field=models.CharField(blank=True, help_text='Type Delete here to cancel', max_length=8, null=True),
        ),
    ]
