# Generated by Django 2.1.3 on 2019-09-03 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0026_auto_20190903_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btutor',
            name='Class',
            field=models.CharField(choices=[('JSS 1', 'jss_one'), ('JSS 2', 'jss_two'), ('JSS 3', 'jss_three'), ('SSS 1', 'sss_one'), ('SSS 2', 'sss_two'), ('SSS 3', 'sss_three')], help_text='Select subject class', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='btutor',
            name='subject',
            field=models.ForeignKey(help_text='Select subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to='result.ASUBJECTS'),
        ),
    ]
