# Generated by Django 2.1.3 on 2019-09-03 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0027_auto_20190903_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor_home',
            name='first_term',
            field=models.ForeignKey(blank=True, help_text='Not editable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first', to='result.BTUTOR'),
        ),
        migrations.AlterField(
            model_name='tutor_home',
            name='second_term',
            field=models.ForeignKey(blank=True, help_text='Not editable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='result.BTUTOR'),
        ),
        migrations.AlterField(
            model_name='tutor_home',
            name='third_term',
            field=models.ForeignKey(blank=True, help_text='Not editable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='result.BTUTOR'),
        ),
    ]
