# Generated by Django 2.1.3 on 2019-09-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0032_auto_20190905_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateTimeField(default='2019-09-05', max_length=200),
        ),
    ]
