# Generated by Django 2.1.3 on 2019-10-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0052_auto_20191008_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOWNLOADFORMAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formats', models.CharField(choices=[(1, 'CSV'), (2, 'PDF')], default=1, help_text='select file FORMAT', max_length=30, null=True)),
                ('created', models.DateTimeField(default='2019-10-13', max_length=200)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='btutor',
            name='created',
            field=models.DateTimeField(default='2019-10-13', max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateTimeField(default='2019-10-13', max_length=200),
        ),
    ]
