# Generated by Django 2.1.3 on 2019-10-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0053_auto_20191013_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadformat',
            name='formats',
            field=models.CharField(choices=[('1', 'CSV'), ('2', 'PDF')], default=1, help_text='select file FORMAT', max_length=30, null=True),
        ),
    ]
