# Generated by Django 2.1.3 on 2019-10-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0054_auto_20191013_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='created',
        ),
        migrations.RemoveField(
            model_name='session',
            name='updated',
        ),
        migrations.AlterField(
            model_name='btutor',
            name='created',
            field=models.DateTimeField(default='2019-10-19', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloadformat',
            name='created',
            field=models.DateTimeField(default='2019-10-19', max_length=200),
        ),
    ]
