# Generated by Django 2.1.3 on 2019-12-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0059_auto_20191222_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='QUESTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='What is the missing question here?', max_length=1000, null=True)),
                ('optionA', models.CharField(default='Undefined', max_length=200, null=True)),
                ('optionB', models.CharField(default='Undefined', max_length=200, null=True)),
                ('optionC', models.CharField(default='Undefined', max_length=200, null=True)),
                ('optionD', models.CharField(default='Undefined', max_length=200, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('teacher_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='result.CNAME')),
            ],
            options={
                'ordering': ('teacher_name',),
            },
        ),
        migrations.AlterField(
            model_name='btutor',
            name='created',
            field=models.DateTimeField(default='2019-12-23', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloadformat',
            name='created',
            field=models.DateTimeField(default='2019-12-23', max_length=200),
        ),
    ]
