# Generated by Django 2.1.3 on 2019-12-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0060_auto_20191223_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questNum',
            field=models.CharField(default='Undefined', max_length=200, null=True),
        ),
    ]
