# Generated by Django 2.1.3 on 2020-04-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0080_auto_20200408_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='btutor',
            name='master_comment',
            field=models.CharField(blank=True, default='He is a responsible and reliable student.', max_length=115, null=True),
        ),
        migrations.AddField(
            model_name='btutor',
            name='principal_comment',
            field=models.CharField(blank=True, default='Fairly good performance, you can do better.', max_length=115, null=True),
        ),
        migrations.AddField(
            model_name='btutor',
            name='resumption',
            field=models.CharField(blank=True, default='Monday January 9, 2017.', max_length=115, null=True),
        ),
        migrations.AlterField(
            model_name='btutor',
            name='created',
            field=models.DateTimeField(default='2020-04-09', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloadformat',
            name='created',
            field=models.DateTimeField(default='2020-04-09', max_length=200),
        ),
    ]
