# Generated by Django 2.1.3 on 2020-04-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0082_auto_20200409_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='asubjects',
            name='resumption',
            field=models.CharField(blank=True, default='Monday January 9, 2017.', max_length=115, null=True),
        ),
    ]
