# Generated by Django 2.1.3 on 2020-04-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0092_auto_20200417_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='fair',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='good',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='poor',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='None', max_length=200, null=True),
        ),
    ]
