# Generated by Django 2.1.3 on 2020-06-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0099_auto_20200618_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btutor',
            name='created',
            field=models.DateTimeField(default='2020-06-23', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloadformat',
            name='created',
            field=models.DateTimeField(default='2020-06-23', max_length=200),
        ),
        migrations.AlterField(
            model_name='qsubject',
            name='aagr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='qsubject',
            name='fagr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='qsubject',
            name='sagr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
