# Generated by Django 2.1.3 on 2020-07-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0111_auto_20200716_0454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qsubject',
            options={'ordering': ('gender', 'student_name')},
        ),
        migrations.AddField(
            model_name='cname',
            name='middle_name',
            field=models.CharField(blank=True, default='Middle nmae', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='btutor',
            name='created',
            field=models.DateTimeField(default='2020-07-20', max_length=200),
        ),
        migrations.AlterField(
            model_name='cname',
            name='first_name',
            field=models.CharField(blank=True, default='First name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='downloadformat',
            name='created',
            field=models.DateTimeField(default='2020-07-20', max_length=200),
        ),
    ]
