# Generated by Django 2.1.3 on 2020-07-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0112_auto_20200720_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='birth',
            field=models.DateField(blank=True, default='2000-10-01', help_text='Date format: MM/DD/YYYY', null=True),
        ),
    ]
